HeroesVillains/Models/Character.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeroesVillains.Models
{
    public partial class Character
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("powerstats")]
        public Powerstats Powerstats { get; set; }

        [JsonProperty("biography")]
        public Biography Biography { get; set; }

        [JsonProperty("appearance")]
        public Appearance Appearance { get; set; }

        [JsonProperty("work")]
        public Work Work { get; set; }

        [JsonProperty("connections")]
        public Connections Connections { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }

        [JsonProperty("error")]
        public string Error { get; set; }
        [JsonProperty("response")]
        public string Response { get; set; }
    }

    public partial class Appearance
    {
        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("race")]
        public string Race { get; set; }

        [JsonProperty("height")]
        public List<string> Height { get; set; }

        [JsonProperty("weight")]
        public List<string> Weight { get; set; }

        [JsonProperty("eye-color")]
        public string EyeColor { get; set; }

        [JsonProperty("hair-color")]
        public string HairColor { get; set; }
    }

    public partial class Biography
    {
        [JsonProperty("full-name")]
        public string FullName { get; set; }

        [JsonProperty("alter-egos")]
        public string AlterEgos { get; set; }

        [JsonProperty("aliases")]
        public List<string> Aliases { get; set; }

        [JsonProperty("place-of-birth")]
        public string PlaceOfBirth { get; set; }

        [JsonProperty("first-appearance")]
        public string FirstAppearance { get; set; }

        [JsonProperty("publisher")]
        public string Publisher { get; set; }

        [JsonProperty("alignment")]
        public string Alignment { get; set; }
    }

    public partial class Connections
    {
        [JsonProperty("group-affiliation")]
        public string GroupAffiliation { get; set; }

        [JsonProperty("relatives")]
        public string Relatives { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Powerstats
    {
        [JsonProperty("intelligence")]
        public string Intelligence { get; set; }

        [JsonProperty("strength")]
        public string Strength { get; set; }

        [JsonProperty("speed")]
        public string Speed { get; set; }

        [JsonProperty("durability")]
        public string Durability { get; set; }

        [JsonProperty("power")]
        public string Power { get; set; }

        [JsonProperty("combat")]
        public string Combat { get; set; }
    }

    public partial class Work
    {
        [JsonProperty("occupation")]
        public string Occupation { get; set; }

        [JsonProperty("base")]
        public string Base { get; set; }
    }

    public class HeroesResponse
    {
        [JsonProperty("response")]
        public string Response { get; set; }

        [JsonProperty("error")]
        public string Error { get; set; }

        [JsonProperty("results-for")]
        public string ResultsFor { get; set; }

        [JsonProperty("results")]
        public List<Character> Results { get; set; }
    }
}

HeroesVillains/Models/ErrorViewModel.cs
using System;

namespace HeroesVillains.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HeroesVillains/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeroesVillains.Controllers
{
    public class ErrorController : Controller
    {
        [Route("Error/{statusCode}")]
        public IActionResult HttpStatusCodeHandler(int statusCode)
        {
            switch (statusCode)
            {
                case 0:
                    ViewBag.ErrorMessage = "Oh, the character you're looking for doesn't exist";
                    break;
                case 404:
                    ViewBag.ErrorMessage = "Oh, the thing than you are looking for doesn't exist in this universe";
                    break;
            }
            return View("NotFound");
        }
    }
}

HeroesVillains/Controllers/HeroVillainController.cs
using HeroesVillains.Helpers;
using HeroesVillains.Interfaces;
using HeroesVillains.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HeroesVillains.Controllers
{
    public class HeroVillainController : Controller
    {
        private IApi<HeroesResponse> _apiCall;
        private IApi<Character> _apiCallChar;
        private IConfiguration _config;
        public HeroVillainController(IApi<HeroesResponse> api, IConfiguration configuration, IApi<Character> apiChar)
        {
            _apiCall = api;
            _apiCallChar = apiChar;
            _config = configuration;
        }
        //Get the characters searching by the name
        public async Task<IActionResult> Index(string search)
        {
            try
            {
                List<Character> characters = new List<Character>();
                if (string.IsNullOrEmpty(search))
                {
                    return View(characters);
                }

                UsingApiHelper helper = new UsingApiHelper(_config);

                HeroesResponse response = await _apiCall.CallApi(helper.CompleteSearchUri(search));
                if (!string.IsNullOrEmpty(response.Response) && response.Response.Equals("error"))
                {
                    ViewBag.Error = response.Error;
                }
                else
                {
                    ViewBag.Search = search;
                    ViewBag.FirstResults = response.Results;

                    characters = response.Results;
                }


                return View(characters);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Error", ex.Message);
            }
        }

        //Get the information of a specific character
        public async Task<IActionResult> CharacterDetail(string search)
        {
            try
            {
                Character character = new Character();
                if (string.IsNullOrEmpty(search))
                {
                    return RedirectToAction("NotFound", "Error");
                }
                
                UsingApiHelper helper = new UsingApiHelper(_config);

                Character response = await _apiCallChar.CallApi(helper.SearchById(search));
                if (!string.IsNullOrEmpty(response.Response) && response.Response.Equals("error"))
                {
                    return RedirectToAction("NotFound", "Error");
                }
                else
                {
                    character = response;
                }

                return View(character);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Error", ex.Message);
            }
        }
    }
}

HeroesVillains/Views/HeroVillain/CharacterDetail.cshtml
@model HeroesVillains.Models.Character

@{
    ViewBag.Title = "CharacterDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div style="margin-top:25px;" class="main-body" s>
    <div class="row justify-content-center  gutters-sm">
        <div style="flex-basis: content;" class="col-xxl-2 col-lg-4 col-md-6 col-sm-12">
            <div class="profile-card" style="margin:0;">
                <img src=@Model.Image.Url class="img img-fluid">
                <div class="profile-name">@Model.Name</div>
                <div class="profile-side">@(Model.Biography.Alignment == "good" ? "Superhero" :"Villian")</div>
                <div class="profile-realname">@Model.Biography.FullName</div>
                <div class="profile-gender">Gender: @Model.Appearance.Gender</div>
            </div>
        </div>
        <div class="col-xxl-5 col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-3">
                <div class="card-body">
                    <h3 class="d-flex align-items-center mb-3">
                        <i class="material-icons mr-2">Details of @Model.Name</i>
                    </h3>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.FullName)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Race</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Appearance.Race != "null" ? Model.Appearance.Race  : "unknown")
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Place of birth</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.PlaceOfBirth != "null" ? Model.Biography.PlaceOfBirth : "unknown")
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">First-appearance</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.FirstAppearance)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Publisher</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.Publisher)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Alignment</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.Alignment)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Alter-egos</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Biography.AlterEgos)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Aliases</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @foreach (string aliases in @Model.Biography.Aliases)
                            {
                                <span>@(aliases + " - ")</span>;
                            }
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">
                            <h6 class="mb-0">Group affiliation</h6>
                        </div>
                        <div class="col-sm-7 text-secondary">
                            @(Model.Connections.GroupAffiliation)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xxl-5 col-lg-4 col-md-12 mb-3">
            <div class="card h-100">
                <div class="card-body">
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="background-color:#FFF">
        
    </div>

</div>

@section Scripts{
    <script>
        const labels = [
            'Intelligence',
            'Strength',
            'Speed',
            'Durability',
            'Power',
            'Combat',
        ];

        const data = {
            labels: labels,
            datasets: [{
                label: 'Powerstats',
                borderColor: @Html.Raw(Model.Biography.Alignment == "good" ? "'rgb(184, 36, 26)'" : "'rgb(53, 56, 222)'"),
                data: [
                    @Html.Raw(Model.Powerstats.Intelligence != "null" ? int.Parse(Model.Powerstats.Intelligence) : 0),
                    @Html.Raw(Model.Powerstats.Strength != "null" ? int.Parse(Model.Powerstats.Strength) : 0),
                    @Html.Raw(Model.Powerstats.Speed != "null" ? int.Parse(Model.Powerstats.Speed) : 0),
                    @Html.Raw(Model.Powerstats.Durability != "null" ? int.Parse(Model.Powerstats.Durability) : 0),
                    @Html.Raw(Model.Powerstats.Power != "null" ? int.Parse(Model.Powerstats.Power) : 0),
                    @Html.Raw(Model.Powerstats.Combat != "null" ? int.Parse(Model.Powerstats.Combat) : 0),
                ],
            }]
        };

        const config = {
            type: 'radar',
            data: data,
            options: {}
        };
    </script>

    <script>

        const myChart = new Chart(
            document.getElementById('myChart'),
            config
        );
    </script>
}

HeroesVillains/Views/HeroVillain/Index.cshtml
@model IEnumerable<HeroesVillains.Models.Character>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model.Count() > 0)
{
    <div id="results" style="padding-left:20px; padding-right:20px">
        @{Html.RenderPartial("ShowSearchResults", (IEnumerable<HeroesVillains.Models.Character>)ViewBag.FirstResults);}
    </div>
}

@if (ViewBag.Error != null)
{
<script>
    window.onload = function () {
        swal("Error!", '@ViewBag.Error', "error");
    }
</script>
}

HeroesVillains/Views/HeroVillain/ShowSearchResults.cshtml
@model List<HeroesVillains.Models.Character>

@{
    void cards(List<HeroesVillains.Models.Character> characters)
    {
        <div class="row" style="align-items:center">
            @foreach (var item in characters)
            {
                <div class="profile-card" onclick="@("window.location.href='/Character/" + item.Id +"'");">
                    <img src=@item.Image.Url class="img img-fluid">
                    <div class="profile-name">@item.Name</div>
                    <div class="profile-side">@(item.Biography.Alignment == "good" ? "Superhero" :"Villian")</div>
                    <div class="profile-realname">@item.Biography.FullName</div>
                    <div class="profile-gender">Gender: @item.Appearance.Gender</div>
                </div>
            }
        </div>
    }
}

@{ cards(Model); }

HeroesVillains/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NotFound</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style=" margin: 0;">
    <div class="background-not-found" >
        <img class="image-not-found" src="~/Assets/images/TitleNotFound.png" />
        <p style="font-size: 80px; font-family: HeroesLegend">404</p>
        <h1 style="font-family:HeroesLegend">@ViewBag.ErrorMessage</h1>
    </div>
</body>
</html>

HeroesVillains/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeroesVillainsCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>

    
    <div class="body-content">
        <div class="jumbotron jumbotron-fluid" style="text-align:center; margin-bottom:0; margin-left:0; margin-right:0">
            <div class="container">
                <img src="~/Assets/images/title.png" class="img-fluid">
                <hr class="my-4">
                <p>You can try searching for "Deadpool"</p>

                @using (Html.BeginForm("Index", "HeroVillain", FormMethod.Post))
                {
                    <div class="form-inline my-2 my-lg-0" style="place-content:center;">
                        <input class="form-control mr-sm-2" name="search" style="max-width: 75%; margin-right: 0px;" type="search" placeholder="Hero or villain name" aria-label="Search" id="txtSearch">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit" id="btnSearch" onclick="setLocalSuggest()">Search</button>
                    </div>
                }

            </div>
        </div>
         @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>